# This file contains information about the device associated with this repo
# This is a .properties file, but is also interpreted as a Makefile,
# so keep the syntax simple: NAME=VALUE
DEV_MFR=SMARTPARTS
DEV_NAME=
DEV_PN=SP104CEF
DEV_VER=
DEV_TAG=SMARTPARTS_SP104CEF
